# =============================================================
# SENTINEL FRAUD DETECTION ENGINE - CONFIGURATION
# =============================================================

# 1. Application Metadata
spring.application.name=sentinel-fraud-detector
server.port=8080

# 2. Redis Connection Settings
# Default is localhost for local development. 
# Change to 'redis' if running inside Docker Compose.
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# 3. Connection Pool Settings (For High Throughput)
# This shows you understand how to scale the application under heavy load
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

# 4. JSON & Serialization
# Ensures that our Transaction objects are mapped correctly to JSON in Redis
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# 5. Logging & Monitoring
# Set to DEBUG to see the sliding window logic and fraud alerts in real-time
logging.level.root=INFO
logging.level.com.scholarship.sentinel=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# 6. Performance Tuning
# Disables the "shutdown" message in the middle of processing
spring.main.log-startup-info=true