version: '3.8'
services:
  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  sentinel-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis-cache
    depends_on:
      - redis-cache